### ISSUE TITLE
event priority

### ISSUE THREAD

**Issue by Clef777** [nyaatrap/renpy-utilities#1]
Hi. 
At the moment priority = 10 will happen before priority = 9.
While the rest of renpy works in the opposite way: think about the init function or the dse module.
NOTE: to say the truth the init function calls it offset. But still having the same logic of "lower numbers happens first" may be more intuitive.

I think that the only action needed to change this is delete the reverse = True while sorting in update_events().

**Comment by nyaatrap** [comment]
Oh yes. I was using Japanese way without thinking about cultural difference, but it's more logical to order a way dse module using, because it's ren'py module. I'll check codes.

**Comment by nyaatrap** [comment]
fixed in 5f8b8382458cab6a9c748610df83c272ceee50e8
