### ISSUE TITLE
save seen_events

### ISSUE THREAD

**Issue by Clef777** [nyaatrap/renpy-utilities#2]
At the moment the seen_events are saved in the function move_pos().

But I think that this is not a good thing to do:
1) I have found a couple of case where I tried to use move_pos before having an event.
2) in the crawl_loop/adventure_loop you use the move_pos after the event is called, this way you save the events seen. But if i jump to another label while inside the called event (for example to exit the dungeon) I will not reach the move_pos() function and so I will not save the event as a "seen" event.
3) having the move function work as a save is not inuitive for people that have to use it

Suggestion: just delete the save line from the move_pos() function and add it in the crawl_loop/adventure_loop before every event call.

**Comment by nyaatrap** [comment]
Thanks, that's a good suggestion. I'm busy on making a new game, but I'll check and fix it when I have time.

**Comment by nyaatrap** [comment]
I split 'seen' into 'happened' and 'done'  in 90fbbddd7ad533b1692a619ef89576001d05a1de
